import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
await p.goto('http://localhost:5199/', { waitUntil: 'networkidle' });
await p.waitForTimeout(400);
await p.keyboard.press('Backquote'); await p.waitForTimeout(150);
await (await p.$('text=+5000 Score')).click();
await p.keyboard.press('Backquote'); await p.waitForTimeout(900);
for (let i = 0; i < 8; i++) await p.keyboard.press('Tab');
await p.waitForTimeout(400);
await p.screenshot({ path: process.argv[2] + '/10-final.png' });
await p.close();
const q = await b.newPage({ viewport: { width: 820, height: 780 }, deviceScaleFactor: 2 });
await q.goto('http://localhost:5199/', { waitUntil: 'networkidle' });
await q.waitForTimeout(700);
await q.screenshot({ path: process.argv[2] + '/11-narrow.png' });
await b.close();
